### ISSUE TITLE
[Question] How to register to gym.envs

### ISSUE THREAD

**Issue by Thuanduonghien** [baturaysaglam/RIS-MISO-PDA-Deep-Reinforcement-Learning#1]
According to guide to register environment.py to gym.envs  as 
https://stackoverflow.com/questions/52727233/how-can-i-register-a-custom-environment-in-openais-gym. 
(1) I do copy  environment.py to MyFolder/venv/site-packages/gym/envs/classical_control 
(2) from gym.envs.classic_control.environment import RIS_MISO_PDA 
(3) gym.envs.registration(     
         id='RIS_MISO_PDA-v0',     
         entry_point='gym.envs.classic_control:RIS_MISO_PDA',     
         max_episode_steps=1000,
)  
==> It can not work, Can you check where I can fix and register environment.py to gym.envs.  
Thank you

**Comment by baturaysaglam** [comment]
the value for the ``entry_point`` parameter in step (3) should be ``gym.envs.classic_control.environment:RIS_MISO_PDA``.

**Comment by baturaysaglam** [comment]
the value for the ``entry_point`` parameter in step (3) should be ``'gym.envs.classic_control.ris_miso:RIS_MISO_PDA'``.

**Comment by Thuanduonghien** [comment]
> the value for the `entry_point` parameter in step (3) should be `gym.envs.classic_control.environment:RIS_MISO_PDA`.

Thank you!
