### ISSUE TITLE
Imperfect CSI

### ISSUE THREAD

**Issue by AhdHazim** [baturaysaglam/RIS-MISO-PDA-Deep-Reinforcement-Learning#5]
Thank you so much for great contribution.

I am wondering about one thing  while I read the code of this paper, which is that you have mentioned that you used Imperfect CSI, but unfortunately due to my ignorance  I could not figure out  how  you represented the imperfect CSI in your code.  I would be thankful if you can explain to me  this point please.

**Comment by baturaysaglam** [comment]
it should be on [this](https://github.com/baturaysaglam/RIS-MISO-PDA-Deep-Reinforcement-Learning/blob/caa723acc81fcdf63407669fc2b10a56ff27f52d/environment.py#L83) line if I'm not wrong.

**Comment by AhdHazim** [comment]
@baturaysaglam  thank you so much for your kind reply!

Could you explain it for me more please as  I could not understand why you divided by 2???

**Comment by baturaysaglam** [comment]
If you want to sample from a complex Gaussian, you have to divide the variance term by 2.

**Comment by AhdHazim** [comment]
Thank you so much!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
